name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: missnoel9/weatherapp:latest



      - name: SSH to Ubuntu Server and Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.WEB_01_IP_ADDRESS }}
          username: ${{ secrets.WEB_01_HOST }}
          key: ${{ secrets.WEB_01_SSHKEY }}
          script: |
            docker pull missnoel9/weather-app:latest
            docker stop weather-app || true
            docker rm weather-app || true
            docker run -d -p 8080:8080 --name weather-app missnoel9/weather-app:latest