name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: missnoel9
          password: MissNoel@1818
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: missnoel9/weather-app:latest

      # - name: Deploy to web-01
      #   uses: appleboy/ssh-action@v0.1.9
      #   with:
      #     host: ${{ secrets.AWS_EC2_IP_ADDRESS }}
      #     username: ${{ secrets.AWS_HOST_USER }}
      #     key: ${{ secrets.PRIVATE_KEY }}
      #     script: |
      #       sudo docker pull peldrige/clockbox:latest
      #       sudo docker stop clockbox || true
      #       sudo docker rm clockbox || true
      #       sudo docker run -d --name clockbox -p 80:80 peldrige/clockbox:latest